name: Alerts frame windows page testing

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - Browser Windows Page
          - Alerts Page
          - Frames Page
          - Nested Frames Page
          - Modal Dialogs Page

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install specific version of Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-chromedriver: true

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Browser Windows Page
        if: github.event.inputs.deployment_target == 'Browser Windows Page'
        run: pytest -s --headless tests/alerts_frame_windows_test.py::TestAlertsFrameWindows::TestBrowserWindowsPage
        continue-on-error: true

      - name: Alerts Page
        if: github.event.inputs.deployment_target == 'Alerts Page'
        run: pytest -s --headless tests/alerts_frame_windows_test.py::TestAlertsFrameWindows::TestAlertsPage
        continue-on-error: true

      - name: Frames Page
        if: github.event.inputs.deployment_target == 'Frames Page'
        run: pytest -s --headless tests/alerts_frame_windows_test.py::TestAlertsFrameWindows::TestFramesPage
        continue-on-error: true

      - name: Nested Frames Page
        if: github.event.inputs.deployment_target == 'Nested Frames Page'
        run: pytest -s --headless tests/alerts_frame_windows_test.py::TestAlertsFrameWindows::TestNestedFramesPage
        continue-on-error: true

      - name: Modal Dialogs Page
        if: github.event.inputs.deployment_target == 'Modal Dialogs Page'
        run: pytest -s --headless tests/alerts_frame_windows_test.py::TestAlertsFrameWindows::TestModalDialogsPage
        continue-on-error: true