name: Run Tests on Interactions Branch

on:
  push:
    branches:
      - interactions_page
  pull_request:
    branches:
      - interactions_page

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Google Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -s --headless tests/interactions_test.py
        continue-on-error: true