name: Run All Tests on Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Remove preinstalled Google Chrome
        if: github.event.inputs.browser == 'chrome'
        run: sudo apt-get remove -y google-chrome-stable

      - name: Install Google Chrome
        if: github.event.inputs.browser == 'chrome'
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 114.0.5735.90

      - name: Create symbolic link to Google Chrome
        if: github.event.inputs.browser == 'chrome'
        run: |
           sudo ln -sf /opt/hostedtoolcache/setup-chrome/chromium/114.0.5735.90/x64/chrome /usr/bin/google-chrome

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -s --headless
